name: Build and test workflow
on:
  push: 
    branches: [ main, development ]
  pull_request: 
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Use Bazel (Windows only)
        if: matrix.os == 'windows'
        run: ./bazel.exe -h
      - name: Use Bazel
        if: matrix.os != 'windows'
        run: bazel -h
