name: CI
on:
  pull_request: 
    branches: [ main, gui ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ windows-latest, self-hosted ]
        os: [ Linux, Windows ]
    steps:
      - name: Cleanup (Others)
        if: matrix.os != 'Windows'
        run: |
          rm -rf src/extern/glfw
          rm -rf src/extern/imgui
      - name: Cleanup (Windows)
        if: matrix.os == 'Windows'
        run: |
          if (Test-Path src\extern\glfw) {Remove-Item -Recurse -Force -Confirm:$false src\extern\glfw}
          if (Test-Path src\extern\imgui) {Remove-Item -Recurse -Force -Confirm:$false src\extern\imgui}
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GLFW_CHECKOUT}}
          submodules: recursive
#      - name: Checkout submodules
#        run: |
#          cd src/extern/glfw
#          git checkout master
#          cd ../imgui
#          git checkout master
#          cd ../../..
#          echo OS: ${{matrix.os}}

      - name: Check gtest existence (windows)
        id: check_gtest_windows
        if: matrix.os == 'windows-latest'
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: "src/extern/googletest/bazel-bin/gtest.lib"
      - name: Build gtest (windows)
        if: steps.check_gtest_windows.outputs.files_exists == 'false' && matrix.os == 'windows-latest'
        run: |
          echo Building gtest ...
          cd src/extern/googletest
          bazel build :gtest
          cd ../../..
          echo "Done !"
      - name: Check gtest existence (other)
        id: check_gtest_other
        if: matrix.os != 'windows-latest'
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: "src/extern/googletest/bazel-bin/libgtest.so"
      - name: Build gtest (other)
        if: steps.check_gtest_other.outputs.files_exists == 'false' && matrix.os != 'windows-latest'
        run: |
          echo Building gtest ...
          cd src/extern/googletest
          bazel build :gtest
          cd ../../..
          echo "Done !"

      - name: Build product
        run: |
          cd src
          bazel build --sandbox_debug :rebosdk

      - name: Test product
        run: |
          cd src
          bazel build --sandbox_debug :unittests
          ./bazel-bin/unittests
