name: CI
on:
  pull_request: 
    branches: [ main, gui ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, self-hosted ]
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GLFW_CHECKOUT}}
          submodules: recursive
      - name: Checkout submodules
        run: |
          cd src/extern/glfw
          git checkout master
          cd ../imgui
          git checkout master
          cd ../../..
      - name: Check gtest existence
        id: check_gtest
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: "src/extern/googletest/.bazel-bin/libgtest.so"
      - name: Build gtest
        if: steps.check_gtest.outputs.files_exists == 'false'
        # Only run when file does not exist
        run: |
          echo Building gtest ...
          cd src/extern/googletest
          bazel build :gtest
          cd ../../..
          echo "Done !"
      - name: Use Bazel (Windows only)
        if: matrix.os == 'windows'
        run: |
          dir "C:\Program Files (x86)"
          cd src
          ./bazel.exe build :rebosdk
      - name: Use Bazel
        if: matrix.os != 'windows'
        run: |
          cd src
          bazel build :rebosdk
