name: CI
on:
  pull_request: 
    branches: [ main, gui ]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GLFW_CHECKOUT}}
          submodules: recursive
          run: |
            cd src/extern/glfw
            git checkout master
            cd ../imgui
            git checkout master
            cd ../../..
      - name: Use Bazel (Windows only)
        if: matrix.os == 'windows'
        run: |
          cd src
          ./bazel.exe build :rebosdk
      - name: Use Bazel
        if: matrix.os != 'windows'
        run: |
          apt-get install --no-install-recommends --no-install-suggests -y libmesa-dev
          cd src
          bazel build :rebosdk
